//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivatTerminalApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int Id { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.DateTime> DateConfirm { get; set; }
        public string uniqueNumber { get; set; }
        public int PaymentId { get; set; }
        public decimal Sum { get; set; }
        public decimal Comission { get; set; }
        public string PaymentNumber { get; set; }
        public int AdvertiserId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Advertiser Advertiser { get; set; }
        public virtual StatusPay StatusPay { get; set; }
    }
}
